[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# No library, only binaries
[dependencies]
engine-core = { path = "../engine-core", features = ["tt_metrics"] }
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
env_logger = { workspace = true }
flate2 = "1.0"
criterion = { version = "0.6", features = ["html_reports"] }
rand = { workspace = true }
rand_xoshiro = { workspace = true }
rayon = "1.10"
